### ISSUE TITLE
would be better if we add website link in the description.

### ISSUE THREAD

**Issue by ferdinandrosario** [rubytogether/rubytogether.org#10]
![screenshot from 2015-03-25 13 01 19](https://cloud.githubusercontent.com/assets/1284503/6819920/111e4268-d2ef-11e4-94cb-5ba0438e727b.png)
It would be better if we add website link in the description to help user to navigate easily without typing the address in the browser.

**Comment by indirect** [comment]
Sorry, I don't know what you mean. Can you give an example?

**Comment by ferdinandrosario** [comment]
@indirect could please see my above message with new pic?

**Comment by indirect** [comment]
Good idea! Done.

**Comment by ferdinandrosario** [comment]
Sorry to bother you again. I will be more happy if you remove rubytogether.org from the description. (feel like duplicated) :smile:

**Comment by ferdinandrosario** [comment]
:thumbsup:
