### ISSUE TITLE
 Monthly Updates

### ISSUE THREAD

**Issue by Schwad** [rubytogether/rubytogether.org#107]
Hello,

As a proud rubytogether member, I figured this was the best place to leave my feedback. 

I would love it if it were possible to have a relatively consistent update on rubytogether happenings around the first week of the month. My concern is that updates slip into being less and less frequent which will become a negative to having future members sign up and may possibly cost you members like myself who may be wondering what is happening with the organization.

*HOWEVER*, I understand this is a labor of love and on open source volunteer (even if we reimburse a bit) crew... And any recommendations for change from membership should be backed by a willingness to personally chip in. 

So instead of a verbose monthly update I am willing to volunteer my time to do a quick monthly blurb laying out the org's incomings and outgoings for members to peruse. 

Then @indirect or someone else with rubytogether can do a more laid out and comprehensive discussion when they are able. 

More than happy to hear your thoughts on this.

**Comment by indirect** [comment]
thanks for the feedback, and thanks for noticing! it’s wonderful to hear that some people actually read and care about the monthly update. we would also love to hear feedback about which parts of the monthly update are meaningful and important to you, and which sections you don’t care as much about.

we’ve given this a lot of thought, and we don’t really want to post pure numbers without any context. the point of ruby together isn’t to pay for hours, the point of ruby together is to make sure that ruby’s infrastructure is maintained and developed and continues to flourish. that means taking the time to write up _why_ we did the work we did, and how that work will be helpful to the ruby community.

that said, slow updates have been on my mind a lot over the last few months, and we’ve been working on speeding up the monthly updates by automating everything that can be automated, over in #91. unfortunately, taking the time to automate things has also slowed things down somewhat. in future months, we expect to be able to run off the monthly reports in the first few days of each month thanks to the increased automation.

**Comment by Schwad** [comment]
André, thanks for the kind words and pointing me to that PR! 

Really enjoyed looking through that code and automation of the updates. :) I love a bit of automation, do you/will you have sharing automation built in as well? (I.e. Shooting out posts to Twitter/Reddit/etc about the update). 

Thanks again for the response and the work you do!

**Comment by Schwad** [comment]
@indirect I'm going to close this for now. Thanks again!

**Comment by indirect** [comment]
@Schwad that's great feedback, thanks! hopefully the next update will go out tonight or tomorrow. :)
