### ISSUE TITLE
replace EY quote 

### ISSUE THREAD

**Issue by cczona** [rubytogether/rubytogether.org#19]
Re  https://github.com/rubytogether/rubytogether.org/app/views/home/index.html.erb 

PJ Hagerty recently moved from EY to Jut.io. The latter isn't a Ruby shop, so unlikely to become a RubyTogether member in the near future. Replacing the quote with one (or more) from a different member would be helpful. I checked in with PJ, and he's amenable.

Suggestions?

**Comment by indirect** [comment]
We could promote a quote from Stripe to the homepage from /companies, or get new quotes from one of: Basecamp, New Relic, Digital Ocean, or Kickstarter

**Comment by LynnCo** [comment]
Change was done here https://github.com/rubytogether/rubytogether.org/commit/883666d4827e0acfd9e61e7ac1e5307c0d05cf01 !
