### ISSUE TITLE
Add Disclaimer for Infographic

### ISSUE THREAD

**Issue by adarsh** [rubytogether/rubytogether.org#203]
Reason for Change
=================
* TLDR: the Fundraising "thermometer" infographic could be misleading regarding the Rubygems.org partnership
* See https://github.com/rubytogether/board/issues/10 for original discussion and detail

Proposed Changes
=======
* Add the following disclaimer: `"This roadmap is for how RubyTogether allocates its budget, it does not include sponsored work on projects by third parties"` or something like that.

cc @practicingdev

**Comment by rubymorillo** [comment]
Closing out this issue! PR https://github.com/rubytogether/rubytogether.org/pull/204 was merged and the disclaimer is live on the site 🎉
