### ISSUE TITLE
"Significant progress" section in homepage needs a revamp

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubytogether/rubytogether.org#456]
Right now it reads like this

>  ### Significant Progress
>
> In our first year, Ruby Together has completed significant improvements to the infrastructure that Ruby developers use every day:
>
> * Shipped Bundler versions 1.10, 1.11, and 1.12, featuring conditional gems, optional groups, and a new gem index that can scale to handle the next five years of gems.
> * Launched Gemstash 1.0, a server that can cache gems for your datacenter or office or host your private gems.
> * Migrated RubyGems.org to use CDN servers around the world to serve data, speeding up gems for everyone.

But Rubytogether is 4 years old now I think. We should probably mention/add other improvements.

**Comment by indirect** [comment]
It's uh... oh man. I think 6 years old? 😬 We should update this! That is a very good idea. 😅

**Comment by deivid-rodriguez** [comment]
Wow, 6 years! Hopefully much more to come :)

**Comment by indirect** [comment]
Language updated in f3f9b173fe9ec435c73e7acaf31357408a807428!

> Significant Progress
> 
> For over six years, Ruby Together as maintained and developed infrastructure for the Ruby programming language:
> 
> Made Bundler faster, more reliable, and less buggy in 1 major, 9 minor, 85 patch, and 27 prerelease versions, while helping merge Bundler into Ruby itself
> Improved RubyGems by fixing bugs, integrating Bundler, and releasing 1 major, 5 minor, 55 patch, and 4 prerelease versions
> Maintained RubyGems.org to provide gems faster and more securely, while providing a record 99.998% uptime for gem downloads from 2015 to 2021
> Funded rebuilding and relaunching The Ruby Toolbox, the most thorough gem reference and comparison site on the internet
> Launched Gemstash, a private gem server that can also cache gems locally for your office or datacenter
