### ISSUE TITLE
Getting the names of new members when running `stats:since`

### ISSUE THREAD

**Issue by LynnCo** [rubytogether/rubytogether.org#55]
I haven't looked into this thoroughly, but it seems to be the case that it only shows the names of companies when they're above a certain $ amount? I figure the same thing is the case for developers? I wanted to clarify that this is the case since `heroku run bin/rake stats:since[2016-06-21] --app rubytogether` is giving me 5 new members but no names

**Comment by indirect** [comment]
Members don't have to include their names when they sign up. Any member who doesn't have a name chose not to give it, but they are contributing at the level stated (which is always $40 for individuals, and fixed for each different company "plan").
