### ISSUE TITLE
Add login page

### ISSUE THREAD

**Issue by indirect** [rubytogether/rubytogether.org#60]
We should let users set passwords and log in with their email and password instead of having to dig out the link we initially emailed them when they signed up.

**Comment by rymcmahon** [comment]
Does this feature already exist (https://rubytogether.org/sign_in)? I'd like to contribute to rt.org but I want to make sure I'm working on something that is needed.

**Comment by adarsh** [comment]
@rymcmahon There is no link to the login page at the very least. That seems to be a helpful addition!
